"""Workspace model: the on-disk home of one plotting session (design.md §4).

The workspace directory is the **only** coupling between better-mad and the agent:

    workspace/
    ├── AGENTS.md      # skill file for the agent harness (SDK reference, rules)
    ├── datasets.md    # auto-generated manifest of loaded datasets
    ├── plot.py        # the active plotting script (agent- and user-edited)
    └── .data/         # per-dataset parquet snapshots consumed by better_mad.sdk

The app watches ``plot.py`` and re-runs it (see :mod:`better_mad.core.runner`);
agent harnesses discover the SDK by reading ``AGENTS.md``. Nothing here touches the UI.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path

import pandas as pd

from better_mad.core.dataset import Dataset, load_dataset
from better_mad.core.loading import ParserSettings

SCRIPT_NAME = "plot.py"
SKILL_FILE = "AGENTS.md"
MANIFEST_FILE = "datasets.md"
DATA_DIR_NAME = ".data"

STARTER_SCRIPT = '''\
"""Plot script — edited by you and the agent; re-runs automatically on save.

See AGENTS.md for the SDK reference and datasets.md for available data.
"""

# import holoviews as hv
#
# import better_mad.sdk as bm
#
# df = bm.data("<dataset name>")  # see datasets.md for names and columns
# fig = hv.Points(df, kdims=["XCORD_MIDPT", "YCORD_MIDPT"])
# bm.show(fig)
'''

_MANIFEST_HEADER = """\
# Datasets

Auto-generated by better-mad — do not edit. Script names are the column names
`bm.data()` returns; originals are shown for reference.

"""

_MANIFEST_EMPTY = _MANIFEST_HEADER + "No datasets loaded yet.\n"


def _skill_template() -> str:
    return resources.files("better_mad.core.templates").joinpath("AGENTS.md").read_text()


@dataclass
class Workspace:
    """A plotting workspace on disk.

    Attributes:
        path: workspace directory.
        datasets: name -> loaded dataset. Names are file stems, de-duplicated
            with ``_2``, ``_3`` suffixes.
    """

    path: Path
    datasets: dict[str, Dataset] = field(default_factory=dict)

    @property
    def script_path(self) -> Path:
        return self.path / SCRIPT_NAME

    @property
    def skill_path(self) -> Path:
        return self.path / SKILL_FILE

    @property
    def manifest_path(self) -> Path:
        return self.path / MANIFEST_FILE

    @property
    def data_dir(self) -> Path:
        return self.path / DATA_DIR_NAME

    def add_file(self, path: str | Path, settings: ParserSettings | None = None) -> Dataset:
        """Load a file into the workspace: parse, snapshot to parquet, refresh manifest.

        The dataset name is the file stem; on collision a numeric suffix is added.
        Raises ``LoaderError`` on unparsable input (nothing is registered).
        """
        ds = load_dataset(path, settings=settings)
        name = ds.name
        n = 2
        while name in self.datasets:
            name = f"{ds.name}_{n}"
            n += 1
        ds.name = name
        ds.df.to_parquet(self.data_dir / f"{name}.parquet")
        self.datasets[name] = ds
        self.refresh_manifest()
        return ds

    def refresh_manifest(self) -> None:
        self.manifest_path.write_text(render_manifest(self.datasets))


def create_workspace(path: str | Path) -> Workspace:
    """Create (or open) a workspace directory.

    Writes the skill file, starter script and manifest where missing; never
    overwrites existing files, so user/agent edits survive re-open.
    """
    root = Path(path)
    ws = Workspace(path=root)
    root.mkdir(parents=True, exist_ok=True)
    ws.data_dir.mkdir(exist_ok=True)
    if not ws.skill_path.exists():
        ws.skill_path.write_text(_skill_template())
    if not ws.script_path.exists():
        ws.script_path.write_text(STARTER_SCRIPT)
    ws.refresh_manifest()
    return ws


def render_manifest(datasets: dict[str, Dataset]) -> str:
    """Render ``datasets.md``: per-dataset column tables with stats."""
    if not datasets:
        return _MANIFEST_EMPTY
    parts = [_MANIFEST_HEADER]
    for name, ds in datasets.items():
        parts.append(f"## {name}\n")
        parts.append(f"- Source: `{ds.path}`")
        parts.append(f"- Rows: {len(ds.df):,} · Columns: {len(ds.df.columns)}")
        parts.append("")
        parts.append("| Original | Script name | dtype | min | max | NaN% |")
        parts.append("|---|---|---|---|---|---|")
        display: dict[str, str] = ds.df.attrs.get("display_names", {})
        for col in ds.df.columns:
            parts.append(_column_row(ds.df, col, display.get(col, col)))
        parts.append("")
    return "\n".join(parts)


def _column_row(df: pd.DataFrame, col: str, original: str) -> str:
    s = df[col]
    dtype = str(s.dtype)
    nan_pct = 100.0 * s.isna().mean()
    if pd.api.types.is_numeric_dtype(s) and s.notna().any():
        lo = f"{s.min():.6g}"
        hi = f"{s.max():.6g}"
    else:
        lo = hi = "—"
    return f"| {original} | `{col}` | {dtype} | {lo} | {hi} | {nan_pct:.1f} |"
